name: Build KPM Module

on:
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: 获取源代码
    uses: actions/checkout@v4

  - name: 获取 KernelPatch 源码
    run: |
      git clone --depth 1 --branch 0.11.3 \
        https://github.com/bmax121/KernelPatch.git \
        ../KernelPatch-0.11.3

  - name: 配置 Android NDK 环境
    uses: nttld/setup-ndk@v1
    id: setup-ndk
    with:
      ndk-version: r25c

  - name: 检查 Kernel 源码
    run: |
      test -f ../android_kernel_modules_and_devicetree_oneplus_sm8450-oneplus-sm8450_b_16.0_oneplus_10_pro/vendor/qcom/opensource/camera-kernel/include/uapi/camera/media/cam_defs.h

  - name: 编译 KPM
    run: |
      export NDK_PATH=${{ steps.setup-ndk.outputs.ndk-path }}
      make NDK_PATH="$NDK_PATH"

  - name: 打包并上传成品
    uses: actions/upload-artifact@v4
    with:
      name: KPM-Output
      path: |
        ./*.kpm
        out/*.kpm
        build/*.kpm
```
